version: "3.8"
services:
  # MySQL database container
  db:
    image: mysql:8.0
    container_name: app_db_laravel_react
    restart: on-failure
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: gigi
      MYSQL_DATABASE: app
      MYSQL_USER: gigi
      MYSQL_PASSWORD: gigi
      # Supprimé MYSQL_ALLOW_EMPTY_PASSWORD pour sécurité (inutile avec root password défini)
    networks:
      - app_laravel_react

  # phpMyAdmin container
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: app_phpmyadmin_laravel_react
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: gigi
      PMA_PASSWORD: gigi
      # Changé PMA_USER à 'gigi' pour correspondre à MYSQL_USER
    networks:
      - app_laravel_react

  # Laravel Apache server container
  app:
    build:
      context: ./docker
    container_name: laravel_app
    restart: on-failure
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./project:/var/www
    ports:
      - "8741:80"
    depends_on:
      - db
    networks:
      - app_laravel_react

  # react frontend container
  react-app:
    build:
      context: ./project/resources/crud-react-vite
      dockerfile: Dockerfile
    container_name: react_app
    restart: on-failure
    ports:
      - "4200:4200"
    volumes:
      - ./project/resources/crud-react-vite:/app
      - /app/node_modules 
    environment:
      VITE_BASE_URI: http://localhost:4200
      NODE_ENV: development
    networks:
      - app_laravel_react
    depends_on:
      - app

networks:
  app_laravel_react:
    driver: bridge

volumes:
  db-data:
